---
version: '3.4'

services:
   whirlpool-client-cli:
    build: 
      context: ./src/whirlpool-client-cli/
      args:
        VERSION: 0.10.17.1  # https://code.samourai.io/whirlpool/whirlpool-client-cli/-/releases
    image: whirlpool-client-cli
    container_name: whirlpool-client-cli
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - 8899:8899
